name: Sync Shared Files

on:
  push:
    branches:
      - main

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Update submodules in target repositories
        run: |
          repos=("ma")

          for repo in "${repos[@]}"
          do
            git clone https://${{ secrets.PAT }}@github.com/ma-cyou/$repo.git
            cd $repo
            
            git submodule update --remote src/lib
            git add src/lib
            git commit -m "Update shared components"
            git push origin main

            cd ..
          done
