name: Sync Shared Components

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Git User Identity
        run: |
          git config --global user.name "ma-cyou"
          git config --global user.email "${{ secrets.EMAIL }}"

      - name: Push changes to target repositories
        run: |
          repos=("ma")
          PAT="${{ secrets.PAT }}"

          for repo in "${repos[@]}"
          do
            git clone https://${PAT}@github.com/ma-cyou/$repo.git
            cd $repo

            if ! git config --file .gitmodules --get-regexp "src/lib/shared" > /dev/null; then
              echo "Submodule not found. Adding it now."
              git submodule add https://github.com/ma-cyou/ma-shared.git src/lib/shared
            fi

            git submodule update --init --remote src/lib/shared
            
            if [[ -n $(git status --porcelain) ]]; then
              git add src/lib/shared
              git commit -m "Update shared components"
              git push origin main || echo "Failed to push to $repo"
            else
              echo "No changes to commit in $repo."
            fi

            cd ..
          done
