name: Sync Shared Files

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name 'ma-cyou'
          git config --global user.email ${{ secrets.EMAIL }}

      - name: Push changes to target repositories
        run: |
          repos=("ma")

          for repo in "${repos[@]}"
          do
            git remote | grep $repo || git remote add $repo https://${{ secrets.PAT }}@github.com/ma-cyou/$repo.git
            git push $repo main || echo "Failed to push to $repo"
          done
